import Topbar from '../components/Topbar';
import { precisionRecallHistory } from '../data/mockData';
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

const alertsByWard = [
  { ward: '4B', alerts: 14 },
  { ward: '2A', alerts: 9 },
  { ward: '1C', alerts: 6 },
];

const outcomeBreakdown = [
  { label: 'True positive', value: 62, tone: 'var(--trace-stable)' },
  { label: 'False positive', value: 18, tone: 'var(--trace-watch)' },
  { label: 'Missed (false negative)', value: 4, tone: 'var(--trace-critical)' },
];

export default function Analytics() {
  return (
    <>
      <Topbar title="Analytics and reports" subtitle="Model performance across all wards" />

      <div className="grid-2" style={{ marginBottom: 16 }}>
        <div className="panel">
          <p className="panel-title">Alerts generated by ward, last 30 days</p>
          <div style={{ height: 200 }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={alertsByWard}>
                <CartesianGrid stroke="var(--line)" strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="ward" tick={{ fill: 'var(--text-dim)', fontSize: 11 }} axisLine={{ stroke: 'var(--line)' }} tickLine={false} />
                <YAxis tick={{ fill: 'var(--text-dim)', fontSize: 11 }} axisLine={false} tickLine={false} />
                <Tooltip contentStyle={{ background: 'var(--bg-card-raised)', border: '1px solid var(--line-strong)', borderRadius: 8, fontSize: 12 }} />
                <Bar dataKey="alerts" fill="var(--trace-accent)" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="panel">
          <p className="panel-title">Outcome breakdown</p>
          {outcomeBreakdown.map((o) => (
            <div key={o.label} style={{ marginBottom: 12 }}>
              <div className="flex justify-between" style={{ marginBottom: 5 }}>
                <span className="text-sm" style={{ color: 'var(--text-secondary)' }}>{o.label}</span>
                <span className="mono text-sm">{o.value}%</span>
              </div>
              <div style={{ height: 7, background: 'var(--bg-panel)', borderRadius: 4 }}>
                <div style={{ width: `${o.value}%`, height: '100%', borderRadius: 4, background: o.tone }} />
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="panel">
        <p className="panel-title">Precision and recall, 30-day trend</p>
        <div style={{ height: 220 }}>
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={precisionRecallHistory}>
              <CartesianGrid stroke="var(--line)" strokeDasharray="3 3" vertical={false} />
              <XAxis dataKey="day" tick={{ fill: 'var(--text-dim)', fontSize: 11 }} axisLine={{ stroke: 'var(--line)' }} tickLine={false} />
              <YAxis tick={{ fill: 'var(--text-dim)', fontSize: 11 }} axisLine={false} tickLine={false} domain={[50, 100]} />
              <Tooltip contentStyle={{ background: 'var(--bg-card-raised)', border: '1px solid var(--line-strong)', borderRadius: 8, fontSize: 12 }} />
              <Line type="monotone" dataKey="precision" stroke="var(--trace-accent)" strokeWidth={2} dot={false} />
              <Line type="monotone" dataKey="recall" stroke="var(--trace-stable)" strokeWidth={2} dot={false} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="flex gap-8 mt-24">
        <button className="btn">
          <i className="ti ti-download" aria-hidden="true"></i> Export PDF report
        </button>
        <button className="btn ghost">
          <i className="ti ti-download" aria-hidden="true"></i> Export CSV
        </button>
      </div>
    </>
  );
}
